### ISSUE TITLE
Installation of Google colab 

### ISSUE THREAD

**Issue by kriaz100** [linkedin/greykite#10]
How I can permanently install greykite on google colab?

**Comment by Reza1317** [comment]
Hi, 

We have not tried Google Colabs in this context. That is probably a question for Google Colab team about the possibility to add a python library to Colab permanently etc.

Thanks
Reza

**Comment by jorgelaranjo** [comment]
Follow this set of instructions. Should allow for a permanent install

https://ayoolafelix.hashnode.dev/how-to-permanently-install-a-module-on-google-colab-ckixqrvs40su044s187y274tc
