### ISSUE TITLE
Predicted values and metrics for N-step ahead forecast.

### ISSUE THREAD

**Issue by ArcticSublime** [linkedin/greykite#106]
Hi,

I am currently working on a task that uses daily data to forecast the next 7 days.
My understanding is that the values of `result.backtest.df_test["forecast"]` and `result.backtest.test_evaluation` are based on one-step ahead forecasts.
How can I get all the forecast values from one to seven days ahead at each point in the test period? Also, is it possible to use the N-step ahead forecast metrics instead of the one-step ahead forecast metrics in the grid search?

Thanks!

**Comment by amyfei2015** [comment]
To forecast for next 7 days, you can specify the `forecast_horizon` to 7. The model shall then predict for next 7 days. Let us know if that helps, thanks! (The documentation is [here](https://linkedin.github.io/greykite/docs/0.5.0/html/pages/stepbystep/0500_output.html#backtest))

**Comment by amyfei2015** [comment]
Hi! The results from `result.backtest` will be predicted by the model trained from `df_train` (so it's also different from Fig. 3(a)), and there is currently no built-in functionality to train multiple models to predict for each time point now.  You will need to run the model repeatedly outside `greykite` to do the backtest as you have in Fig. 3(b). 

One trick on running t+7d model to save speed is that if you only need to look at the forecast right on the 7th day but not the days before, you can set `forecast_one_by_one` in `model_components_param` to `False`.

Let us know if you have more questions on this, thanks!

**Comment by amyfei2015** [comment]
Hi! Actually you can use the `benchmarking` class to get the results you want. Please check [here](https://linkedin.github.io/greykite/docs/0.5.0/html/gallery/quickstart/03_benchmark/0200_benchmark.html#sphx-glr-gallery-quickstart-03-benchmark-0200-benchmark-py)!

**Comment by ArcticSublime** [comment]
Hi @amyfei2015, the second half of the [Compare forecasts](https://linkedin.github.io/greykite/docs/0.5.0/html/gallery/quickstart/03_benchmark/0200_benchmark.html#compare-forecasts) in your link seems to be exactly the result I need.

Thank you so much!
