### ISSUE TITLE
Importing Forecaster gives error for United States class (Holiday?)

### ISSUE THREAD

**Issue by sarkistashjian** [linkedin/greykite#108]
Hello, I have been running greykite for months and I got a new error which has never been an issue before when I import Forecaster. Here is a screenshot of the details. Is there a fix here I am unaware of? I am running greykite 0.5.0
![greykite_error](https://github.com/linkedin/greykite/assets/102757608/67d007c2-8e77-4497-b256-fb36341da5cc)

**Comment by sayanpatra** [comment]
Thanks for the diagnosis @bhatt-priyadutt.
@sarkistashjian Does pinning down the `holidays` version resolve the issue?
You can pin the version here: https://github.com/linkedin/greykite/blob/8c87e36db9c812cf6baf2da61b5bb940fe30c3d4/setup.py#L15

**Comment by sarkistashjian** [comment]
yes, I believe this fixed it! I used !pip install holidays==0.24 @sayanpatra 

Thank you, @bhatt-priyadutt

**Comment by sayanpatra** [comment]
Thanks, closing the ticket.
