### ISSUE TITLE
 ValueError: ``MULTISTAGE_EMPTY`` can not be used without overriding.

### ISSUE THREAD

**Issue by toymoshoma** [linkedin/greykite#114]
How does one resolve this error: " **ValueError: ``MULTISTAGE_EMPTY`` can not be used without overriding. You must provide parameters in ``ModelComponentsParam.custom.multistage_forecast_configs``.**" when implementing multistage forecasting using **'MULTISTAGE_EMPTY'** ?. I am practising based on the Multistage Forecasting tutorial.

![image](https://github.com/linkedin/greykite/assets/68965294/23413aa7-e63b-45e7-864e-181e7acbba09)

**Comment by KaixuYang** [comment]
Hi @toymoshoma could you try `SILVERKITE_WOW` instead of `MULTISTAGE_EMPTY`? The latter requires explicitly specifying the configuration, while the former has some preset parameters.

**Comment by toymoshoma** [comment]
Noted Thank you
