### ISSUE TITLE
Figure not showing in plotly.io.show()

### ISSUE THREAD

**Issue by hsugoken** [linkedin/greykite#13]
I am trying to use the simple_forecast notebook from the quickstart but when running `plotly.io.show(fig)` no image is coming here. There is no error being thrown. 
![Screenshot from 2021-05-25 11-56-06](https://user-images.githubusercontent.com/80521644/119449658-887f2780-bd50-11eb-8877-56f4d3b52314.png)

**Comment by jorgelaranjo** [comment]
```
import plotly.offline as pyo
pyo.init_notebook_mode()
```

**Comment by al-bert** [comment]
Thanks for chiming in @jorgelaranjo ! Yes, we put some instructions for interactive plotting here: https://linkedin.github.io/greykite/installation.html

To render plots in the notebook, use notebook mode and replace `plotly.io.show` with `iplot`:
```
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)  # for plots to render in jupyter notebook
# ... notebook code ...
# plotly.io.show(fig)  # replace these with `iplot`
iplot(fig)
```

**Comment by hsugoken** [comment]
> ```
> import plotly.offline as pyo
> pyo.init_notebook_mode()
> ```

Thank you
