### ISSUE TITLE
Installing Greykite breaks Prophet

### ISSUE THREAD

**Issue by raffg** [linkedin/greykite#16]
Installing Greykite in the same env as Prophet causes problems due to different versions of the Holidays package.
Greykite requires `holidays==0.9.10`, whereas Prophet requires `holidays>=0.10.2`. Is there any reason Greykite can't use the more recent `holiday` package?

**Comment by Reza1317** [comment]
Thanks for raising this issue. We are looking into unpinning some of these packages (which are related to prophet installation) to resolve these installation issues.  This should be resolved in the next release and we hope to do so in a timely fashion.

**Comment by KaixuYang** [comment]
@raffg We just updated `greykite==0.2.0` which unpins `fbprophet` and `holidays`, see the comments in #11 . Thanks for raising this issue.
