### ISSUE TITLE
Greykite suitable for pure linear increasing series?

### ISSUE THREAD

**Issue by akthammomani** [linkedin/greykite#18]
Hello 

I'm working in some house price time series using Greykite but for some reason, the forecast I got is just a median price between upper and lower (ARIMA),  so is this known issue with Greykite when we have a pure linear increasing series? 

Thank you 
Aktham Momani
![greykite_forecast](https://user-images.githubusercontent.com/67468718/120943658-237ae880-c6e5-11eb-9a42-b5b2d381e7c4.JPG)

**Comment by akthammomani** [comment]
![greykite_forecast](https://user-images.githubusercontent.com/67468718/120943546-5f617e00-c6e4-11eb-9900-d94ca69d8c93.JPG)

**Comment by akthammomani** [comment]
Data frequency is monthly so I used freq="MS" as showing below: 

Please let me know if additional information is needed.

# specify dataset information
metadata = MetadataParam(
                                              time_col="ts",  # name of the time column 
                                              value_col="y",  # name of the value column 
                                              freq="MS"   #"MS" for Monthly at start date, "H" for hourly, "D" for daily, "W" for weekly, etc.       
                                              )

# Creates forecasts and stores the result
forecaster = Forecaster()  

# result is also stored as `forecaster.forecast_result`.
result = forecaster.run_forecast_config(  
                                                             df=df,
                                                             config=ForecastConfig(
                                                             model_template=ModelTemplateEnum.SILVERKITE.name,
                                                             forecast_horizon=12,  # forecasts 12 steps ahead
                                                             coverage=0.95,           # 95% prediction intervals
                                                             metadata_param=metadata
                                                                                                  )
                                                               )


snapshot of the data used: 

ts    datetime64[ns]
y     float64

	ts	                  y
0	2012-02-01	390000.0
1	2012-03-01	400000.0
2	2012-04-01	410000.0
3	2012-05-01	438000.0
4	2012-06-01	470000.0
...	...	...
106	2020-12-01	1030000.0
107	2021-01-01	1050000.0
108	2021-02-01	1085000.0
109	2021-03-01	1095000.0
110	2021-04-01	1125000.0

Regards,
Aktham

**Comment by sayanpatra** [comment]
@akthammomani `Silverkite` tries to automatically introduce some amount of seasonality to the model. However, it is probably redundant for your use case. You can try to:

1. Tune the seasonality (maybe even turn those off). Example here: https://github.com/linkedin/greykite/blob/master/docs/nbpages/tutorials/0100_forecast_tutorial.py (line 446)
2. Use a different template e.g. `SILVERKITE_WEEKLY`. It was tuned for weekly data, however might produce a better model than `SILVERKITE`. More details here: https://github.com/linkedin/greykite/blob/master/docs/pages/stepbystep/0200_choose_template.rst

**Comment by akthammomani** [comment]
Both of the suggestions, results same initial forecast, as shown below:

![seasonality_off](https://user-images.githubusercontent.com/67468718/122967687-94eea400-d33f-11eb-97f6-3b6b167a47ae.JPG)

**Comment by sayanpatra** [comment]
@akthammomani Can you try using SILVERKITE_EMPTY template with C(month) as a regressor, ct1 as growth, and autoregression with "auto" or lag 1

**Comment by KaixuYang** [comment]
Close this issue as this thread has been inactive for many days.
