### ISSUE TITLE
uncertain futures

### ISSUE THREAD

**Issue by MaximeTuab** [linkedin/greykite#24]
hi,
first, thank you for this amazing work!!!
Let's say I want to make some predictions over a future that is uncertain (e.g. my future might be based on 2 hypothesis, "France will win Euro", "France will not win Euro" 😥).
In that case, I have 2 data-frames with different regressors.
I can make independant predictions over each of these data-frames.
But I am interested into aggregating these two predictions (in real life, much more than 2) into one prediction, managing median value, uncertainty intervals, etc.
Is there a way to do that?
Thank you!
M.

**Comment by al-bert** [comment]
Great question! (and devastating penalty shootout for France a few days ago..)

In this case, you would make multiple forecasts with greykite (and any other library) and then apply your own method to generate the consensus forecasts.

It _might_ be possible to stretch the usage of `ReconcileAdditiveForecasts` to generate such consensus, by creating a "tree" where each parent has a single child, but we haven't tried it ourselves. The consensus forecast would then be a linear combination of the input forecasts. See https://github.com/linkedin/greykite/issues/25 for a brief description of that method if interested. Before going too deep into this, I'd recommend starting with a simpler method like median, as you mentioned, and making sure your input forecast are good.
