### ISSUE TITLE
Forecast with multiple/grouped/hierarchical time series

### ISSUE THREAD

**Issue by reidfalconer** [linkedin/greykite#25]
Say one had a dataset of demand of several products (1200 products) for over 5 years (weekly) and needed to forecast the demand of each product. Is there a way to train product specific models and forecast at the product level? 

Additionally, is here a way to do hierarchical forecasting? For example if we have a hierarchical listing of different products can we then do forecasting both at the base level (i.e. for each individual products time series) and at aggregate levels defined by the product hierarchy? 

This would require us to reconcile the forecasts at the different levels (using Top Down, Bottom Up, Optimal Reconciliation, etc...). I see that there is a `reconcile_forecasts.py` and a `hierarchical_relationship.py` but no documentation on these implementations. 

Thanks in advance.

**Comment by al-bert** [comment]
Great questions! Could you provide some more detail about the "product specific models" you'd like to train? Silverkite is univariate, but you can share basic information between forecasts using common regressors or hyperparameters.

For the second question, the `ReconcileAdditiveForecasts` class can be used to reconcile forecasts to satisfy additive constraints, such as your additive product hierarchy. In brief, it takes the base (independent) forecasts and adjusts them to minimize forecast error, reconstruction error, and a few other terms. It also supports the standard bottom up and OLS methods. This is a newer feature so we don't have a tutorial yet, but you are welcome to try it out. See the docstrings and test cases for `reconcile_forecasts.py` and  `hierarchical_relationship.py`.

**Comment by KaixuYang** [comment]
Close this issue as this thread has been inactive for many days.
