### ISSUE TITLE
TimeSeries features

### ISSUE THREAD

**Issue by ggerogiokas** [linkedin/greykite#27]
Hi all,

Great library and work!  I was curious if there is a recommended way to get the time series features as a dataframe without running the model?  I am looking to compare with other models.

Thanks,
George

**Comment by Sigvesor** [comment]
Hi,

If I understand your question correct you want a to access the df_features without running the model?
If so:

Suppose you have your dataframe, df, which contains the columns "ts" and "y"

Run:

from greykite.common.features.timeseries_features import build_time_features_df

df_features = build_time_features_df(
    dt=df["ts"],
    conti_year_origin=convert_date_to_continuous_time(df["ts"][0])
)

**Comment by ggerogiokas** [comment]
Hi,

Thanks, I think that generates most of the features.  How would I also get the rest of the features I see in the summary_model function.

Thanks,

**Comment by KaixuYang** [comment]
Hi @ggerogiokas, the `build_time_features_df` method generates all time-related features, which are not necessarily all included in the forecast model. If you are thinking to get the corresponding feature df given a `ForecastConfig`, currently we don't have a function to directly extract the built features, but a workaround could be fitting the fastest linear model with cross-validation turned off. You could add

```
custom=dict(
                fit_algorithm_dict={
                    "fit_algorithm": "linear"
                }
            )
```
to `ModelComponentsParam` and add

```
evaluation_period_param=EvaluationPeriodParam(
            cv_max_splits=0
        )
```
to `ForecastConfig` to speed up the fitting process. Then you can get the dataframe from

```
forecaster.forecast_result.model[-1].model_dict["x_mat"]
```

**Comment by ggerogiokas** [comment]
Hi @KaixuYang,  thanks for the advice I will try that!
