### ISSUE TITLE
Training the model on all data

### ISSUE THREAD

**Issue by Sigvesor** [linkedin/greykite#28]
Hello,

First of all, thanks for this library!

I want to train the model on all of my data, then create a future dataframe and let the model forecast those timesteps. This is to simulate a real-world situation where you actually want to predict the future, in which you don't have any data to validate on. 

The last timestamp in my dataset is 2020-02-20 09:00:00. So I set the train_end_date to this timestamp in MetadataParam like this:

metadata = MetadataParam(
    time_col="ts",
    value_col="y",  
    freq="H",
    train_end_date=datetime.datetime(2020, 2, 20, 9) 
)

Then, in forecaster.forecast_config, I tried commenting out forecast horizon, which needs to be >= 1. 

forecaster = Forecaster()  # Creates forecasts and stores the result
result = forecaster.run_forecast_config(
    df=df_model,
    config=ForecastConfig(
        model_template=ModelTemplateEnum.SILVERKITE.name, # model template
        #forecast_horizon=1, 
        coverage=0.95,  # 95% prediction intervals
        metadata_param=metadata,
        model_components_param=model_components,
        evaluation_period_param=evaluation_period
    )
)

Running this I get the Error message:
ValueError: ``fut_df`` must be a dataframe of non-zero size.

So the closest I have come to achieve what I want is to set train_end_date=datetime.datetime(2020, 2, 20, 8), an hour before the last timestamp in the dataset, and use forecast_horizon=1. However, I still want the model to train on this last hour, since I intend to run a short-term forecast. 

So, the question I have is; how do I train the model on all of my data, without forecasting on it before I give the model a future dataframe?

**Comment by KaixuYang** [comment]
Hi @Sigvesor what does your `df_model` look like? If the last available date in your `df_model` is `2020-2-20 9:00:00`, then you don't have to explicitly specify the `train_end_date`. The `forecast.forecast_result.forecast` includes the forecasted values in the future period (starting 2020-2-20 10:00:00). And you can also use `forecaster.model.predict` on any future data frame similar to `df_model`.

The error looks like there are regressor columns in your model and the future values were not provided? Could you confirm that?

**Comment by Sigvesor** [comment]
Hi @KaixuYang, thanks for the reply. 

You are correct, I have regressor columns. The df_model I give run_forecast_config() consist of the columns "ts", "y", "regressor1", "regressor2". 

regressors = {
    "regressor_cols": ["regressor1", "regressor2"]
}

All columns has the same last timestep 2020-2-20 9:00:00. I can confirm that future values are not provided. Am I supposed to give the future values in run_forecast_config() ? I though I would merge the future values of the regressors with the future dataframe and run forecaster.model.predict on this. This was how I used to proceed with fbprophet. What am I missing here?

**Comment by KaixuYang** [comment]
@Sigvesor When you run `run_forecast_config`, the method

- fits cross-validation
- fits train/test split
- fits model on entire data
- generates prediction for the future period (specified by `forecast_horizon`) based on the model fitted on entire data

So you don't have to call `predict` on yourself. If you include the future rows in the `df_model`, leaving the values to be NA and including the regressor future values, the forecast will be generated automatically and stored in `forecast_result.forecast`. And you can make forecast on different time period by calling the `forecast_result.model.predict` method.

**Comment by Sigvesor** [comment]
@KaixuYang, 

Perfect, thanks for the help!

**Comment by Petrified799** [comment]
Is it the same for Univariate data as well? 

> @Sigvesor When you run `run_forecast_config`, the method
> 
> * fits cross-validation
> * fits train/test split
> * fits model on entire data
> * generates prediction for the future period (specified by `forecast_horizon`) based on the model fitted on entire data
> 
> So you don't have to call `predict` on yourself. If you include the future rows in the `df_model`, leaving the values to be NA and including the regressor future values, the forecast will be generated automatically and stored in `forecast_result.forecast`. And you can make forecast on different time period by calling the `forecast_result.model.predict` method.
