### ISSUE TITLE
Inclusion of custom events, into the model itself with anomaly/holiday score for interpolation.

### ISSUE THREAD

**Issue by beginner1729** [linkedin/greykite#29]
Hey, I am working on a use case that requires a lot of event based forecasting.

Event may range from a technical updation to that of the release of new campaign, but the dates are generally known to business beforehand. Now these events does not follow any calendar rules but data has seen such type of events in the past, so putting those holidays/events in the model itself with custom future date/strength (as all campaigns or event of same genre will have the same type of impact) make the prediction really smooth as no extra added steps are to be done after prediction to tune out the holidays, all will be taken care of in the predict function.

I had already raised an issue in the prophet community [here](https://github.com/facebook/prophet/issues/1873) which is a detailed discussion along with required code snippets. Please let me know if you are thinking to incorporate such changes. This will be really handy for event driven forecasting.

**Comment by al-bert** [comment]
Thanks for asking, this is an interesting application. The best way to handle this is to add a regressor with the holiday "strength" on each day. I think regressors provide the right level of abstraction in Greykite to support your use case and others
