### ISSUE TITLE
Sample distribution

### ISSUE THREAD

**Issue by jonhue** [linkedin/greykite#30]
I wanted to ask whether there is a way to access the distribution of samples (i.e. the assumed model distribution). Reading through https://linkedin.github.io/greykite/docs/0.1.0/html/pages/model_components/0900_uncertainty.html I gathered that Silverkite does some sampling to estimate the uncertainty intervals. Is there a way to access the samples directly, or even better a density over the possible values?

In Prophet, one can use `predictive_samples` to obtain the generated samples.

**Comment by KaixuYang** [comment]
Hi @jonhue by default Silverkite uses normal distribution based confidence intervals and does not have sampling. If you update to the latest Greykite (0.2.0) you can see the estimated standard errors in the prediction df.

**Comment by jonhue** [comment]
@KaixuYang sounds good, thanks for your speedy response!
