### ISSUE TITLE
Grid search range of values

### ISSUE THREAD

**Issue by andrewsx** [linkedin/greykite#31]
Hello, 

Is there a range of values that you would recommend to search over for each of these hyperparameters? 
Thanks!
```
seasonality = {
     "yearly_seasonality": [10, 20],
     "quarterly_seasonality": False,
     "monthly_seasonality": False,
     "weekly_seasonality": False,
     "daily_seasonality": False
 }

 changepoints = {
     "changepoints_dict": None
 }

 # Specifies custom parameters
 custom = {
     "fit_algorithm_dict": {"fit_algorithm": "linear"}
 }

 # Hyperparameter override can be a list of dictionaries.
 # Each dictionary will be one set of hyperparameters.
 override = [
     {},
     {
         "estimator__changepoints_dict": {"method": "auto"},
         "estimator__fit_algorithm_dict": {"fit_algorithm": "ridge"}
     }
 ]
```

**Comment by KaixuYang** [comment]
Hello @andrewsx it's hard to suggest parameter ranges without seeing the data. A general guideline for seasonality is that you can decide by observing the time series whether there is every type of seasonality in the data. For example,  yearly around 10-15 would be good in general, for weekly it's 3-5. The greater the number, the more flexible the seasonality is. For changepoints, I would recommend you look at the [Changepoints](https://linkedin.github.io/greykite/docs/0.1.0/html/gallery/quickstart/0200_changepoint_detection.html#sphx-glr-gallery-quickstart-0200-changepoint-detection-py) section in the documentation to tune the parameters. For fitting algorithms, you can also try "ridge" in additional to "linear". You can start with these parameters and ignore "override".

Kaixu

**Comment by KaixuYang** [comment]
Close this issue as this thread has been inactive for many days.
