### ISSUE TITLE
Predictions taking too long

### ISSUE THREAD

**Issue by lrosariov** [linkedin/greykite#33]
Hi Greykite Team!

I am trying to use Greykite to predict at scale and I am not sure if I am doing something wrong but even with the example code, the predictions take a long time to calculate. Sometime in the 20, 30, 40 seconds and others in the minutes. Any help will be greatly appreciated. Below is a sample code I am running that takes about 17 or so seconds.

from greykite.framework.templates.autogen.forecast_config import ForecastConfig
from greykite.framework.templates.autogen.forecast_config import MetadataParam
from greykite.framework.templates.forecaster import Forecaster
from greykite.framework.templates.model_templates import ModelTemplateEnum
import numpy as np
import pandas as pd
np.random.seed(1)

rows,cols = 365,1
data = np.random.rand(rows,cols)
tidx = pd.date_range('2019-01-01', periods=rows, freq='MS')
data_frame = pd.DataFrame(data, columns=['y'], index=tidx)
data_frame = data_frame.reset_index()
data_frame.columns = ['ts', 'y']

metadata = MetadataParam(
    time_col="ts",     # time column in `df`
    value_col="y"      # value in `df`
)
forecaster = Forecaster()  # creates forecasts and stores the result
forecaster.run_forecast_config(
     df=data_frame,
     config=ForecastConfig(
         # uses the SILVERKITE model template parameters
         model_template=ModelTemplateEnum.SILVERKITE.name,
         forecast_horizon=365,  # forecasts 365 steps ahead
         coverage=0.95,         # 95% prediction intervals
         metadata_param=metadata
     )
 )

forecaster.forecast_result

**Comment by sayanpatra** [comment]
You can significantly reduce runtime by 

1. Using all available CPU cores (Silverkite uses a single core by default).
2. Reducing CV splits or skipping cross-validation (not recommended). Make sure to cross-validate your model thoroughly on sample datasets beforehand. To do this:

```
computation = ComputationParam(
        hyperparameter_budget=None,
        n_jobs=-1,  # to debug, change to 1 for more informative error messages
        verbose=3)

evaluation_period = EvaluationPeriodParam(
        cv_max_splits=0, 
    )
        
result = forecaster.run_forecast_config(
        df=data_frame,
        config=ForecastConfig(
              # uses the SILVERKITE model template parameters
              model_template=ModelTemplateEnum.SILVERKITE.name,
              forecast_horizon=365, # forecasts 365 steps ahead
              coverage=0.95, # 95% prediction intervals
              metadata_param=metadata,
              evaluation_period_param=evaluation_period,
              computation_param=computation
```

Also, the training time does not scale linearly with input data points. e.g. with 3 years of input data, the training time does not increase 3 times.

**Comment by lrosariov** [comment]
Thanks for the quick reply! I have a big cpu cluster setup and it uses all available cores when computing the forecast so that seems to be working as expected. With parallel and removing CV it reduces it but still takes about 6 seconds. What is the typical time for predictions you see in general for Greykite/Silverkite? Is it always in the seconds?

**Comment by sayanpatra** [comment]
Great, you can optimize the total runtime by experimenting with parallelization of Silverkite CV and the total number of time series you want to forecast.

For a single time series, the runtime depends on the amount of training data, forecast horizon and the number of CV splits, but it is in seconds. Silverkite's runtime is comparable to Auto-Arima (Table 1 [here](https://engineering.linkedin.com/blog/2021/greykite--a-flexible--intuitive--and-fast-forecasting-library) ) while providing additional features (e.g. holiday effects). Let us know if you found another library suitable for your use case.

**Comment by lrosariov** [comment]
Gotcha. We are trying to predict a big number of time series in a short amount of time so that's why execution time is very important. I will keep tweaking and exploring. Thanks for the quick response and the guidance.
