### ISSUE TITLE
Getting this error "ValueError: zero-size array to reduction operation minimum which has no identity" ussing lasso 

### ISSUE THREAD

**Issue by martinmenchon** [linkedin/greykite#34]
Hi everyone I'm having this error sometimes when it executes the function summary = result.model[-1].summary() with fit_algorithm: lasso and cv_max_splits: 2

Error: 
**ValueError: zero-size array to reduction operation minimum which has no identity during lasso** 

 For the same data, sometimes it works well and sometimes it fails. I think it's doing a min.reduce of an empty array. 
 Does anyone know how to solve it?
 
 Regards!

Edit: 
The code inside model_summary_utils
confidence_intervals = []
    for i in range(beta_estimates.shape[0]):
        if (beta_estimates[i] == 0).all():
            confidence_intervals.append([0., 0.])
        else:
            check_index = (p_value_rankings[i] > gamma_min) & (beta_estimates[i] != 0)
            if len(check_index) == 0:
                confidence_intervals.append([0., 0.])
            else:
                    lb = np.min(ordinary_confidence_interval_lb[i, check_index])
                    ub = np.max(ordinary_confidence_interval_ub[i, check_index])
                    confidence_intervals.append([lb, ub])

**The problem is that ordinary_confidence_interval_lb[i, check_index] is empty**

**Comment by KaixuYang** [comment]
Hi @martinmenchon This seems to be a bug in our code. We should replace the
```
if len(check_index) == 0
```
with
```
if check_index.sum() == 0
```
We will fix this bug in the next release. Meanwhile you could directly modify the source code under you python environment as a temporary fix.

Thanks for raising this issue!

Kaixu

**Comment by martinmenchon** [comment]
Thank you very much!
I  really appreciate this library
Thanks for the quick response!
