### ISSUE TITLE
pickling greykite model

### ISSUE THREAD

**Issue by ggerogiokas** [linkedin/greykite#36]
Hi again,

Thanks for the package!  

I was having trouble pickling the `results.model` object, I guess there isn't any particular way to do that yet?

I tried using the dump_obj utility I found but got the following error:
![image](https://user-images.githubusercontent.com/12640374/128699942-3287cd01-8d59-4e0b-abe6-e9939cad3503.png)

Best,
George

**Comment by KaixuYang** [comment]
Hi George, it looks like you are running on windows. Seems like windows has different file system and we haven't specifically put efforts in this area. We will investigate into this. Meanwhile if you could try this on linux (such as a vm) the problem should be gone!

Best,
Kaixu

**Comment by ggerogiokas** [comment]
Hi Kaixu,

Thanks for the tip, I will try on a Linux box.

Best,
George
