### ISSUE TITLE
ModuleNotFoundError: No module named 'greykite.framework'; 'greykite' is not a package

### ISSUE THREAD

**Issue by Misha123457** [linkedin/greykite#37]
Hi Community, after installing with pip install greykite, when trying to compile basic project,  the following error message: "ModuleNotFoundError: No module named 'greykite.framework'; 'greykite' is not a package"
When trying to install Python 3.7.7- same error

**Comment by KaixuYang** [comment]
Hi @Misha123457 are you running the code from a directory which has a subdirectory with name "greykite"? It may cause the import fail to find the installed greykite package.

**Comment by Misha123457** [comment]
Thank you for reply, @KaixuYang. I tried to run the same code in  JupyterNotebooks- everything works. So likely, the problem is with Spyder IDE, that I use. Maybe, they require some kind of registration of packages/libraries,,

**Comment by KaixuYang** [comment]
Glad it works!
