### ISSUE TITLE
ERROR: Failed building wheel for scs

### ISSUE THREAD

**Issue by Misha123457** [linkedin/greykite#39]
When trying to install : pip install greykite: 
----------------------------------------
"  ERROR: Failed building wheel for scs
Failed to build scs
ERROR: Could not build wheels for scs which use PEP 517 and cannot be installed directly"

**Comment by KaixuYang** [comment]
Hi @Misha123457 what's your environment?

**Comment by Misha123457** [comment]
yeah, thanks Kaixu, I have resolved by switching to Python 2.7
