### ISSUE TITLE
Need help benchmarking? 

### ISSUE THREAD

**Issue by microprediction** [linkedin/greykite#4]
Hi devs, 

I'm pleased to see another open-source package that looks to be very well documented. Congrats on the hard work. 

I noticed you asked for suggestions of time series on your README, and benchmarking. I sporadically add things to some time series benchmarking at 
https://microprediction.github.io/timeseries-elo-ratings/html_leaderboards/univariate-k_003.html
and hopefully, I'll get around to that (this amounts to calling greykite using the "skater" syntax explained in the timemachines package README). 

On the other hand, if you just want some time series to use to benchmark yourself, you can just grab whatever you want from https://www.microprediction.org/browse_streams.html and see https://www.microprediction.org/features.html for the API (or you can use the microprediction client too)

Anyway, let me know if I can help. 

Peter

**Comment by Reza1317** [comment]
Hi Peter,

That would be great if you could do some bench marking on your end. We will also look at your data to see if we can use them in future bench-marking on our end.

Best,
Reza
