### ISSUE TITLE
Trying to put greykite to Docker

### ISSUE THREAD

**Issue by Misha123457** [linkedin/greykite#40]
Hi team, can you suggest some basic docker image to put Kite into

I am trying to install everything to: continuumio/miniconda3, but 
when I am running: conda install -c msys2 libpython m2w64-toolchain- it fails

**Comment by KaixuYang** [comment]
Hi @Misha123457 Sorry it looks like this question is out of our skill set to help. Maybe you could ask the questions in some Docker forums?

**Comment by kenzie-q** [comment]
Hi @martinmenchon 

Try putting the following at the top of your docker file.

RUN apt update -y &&\
    apt install build-essential -y &&\
    apt-get install manpages-dev

RUN pip install --upgrade setuptools &&\
    pip install --upgrade pip wheel &&\
    pip install --ignore-installed \   #add all pip install packages on next line.

Hope this helps!

**Comment by Misha123457** [comment]
Thanks!

ср, 20 окт. 2021 г., 21:34 McKenzie Quinn ***@***.***>:
