### ISSUE TITLE
Load Model from a GCP Cloud Function 

### ISSUE THREAD

**Issue by kenzie-q** [linkedin/greykite#41]
I'm trying to deploy my greykite model on GCP via a cloud function. The existing read and write functions only work for local directories and not cloud blob storage options. I've adjusted the write function to write to cloud storage but the load function is proving to be a bit challenging.

**Comment by KaixuYang** [comment]
Hi @kenzie-q I'm not familiar with GCP or cloud function. What are the challenges? Is it a linux environment? Would you be able to use the current functions to write to local storage, compress into tar, then upload to cloud storage?

**Comment by kenzie-q** [comment]
Hi @KaixuYang , 

So a cloud function on GCP has a max run time of 10 minutes, and there is no local memory. Therefore we can't use the existing code to read in the model from cloud storage. Writing the model to Cloud storage isn't the issues. I was able to write a function that read all the files and directories to storage. I was also able to edit the existing load function to read from storage, however, it takes longer than 10 minutes to run unfortunately. I'm not sure if there is a way to speed up the process. I'm trying to commit the existing code I have to this repo to be of assistance.

**Comment by KaixuYang** [comment]
Hi @kenzie-q Thank you for the detailed info and code contribution. It's great that you find a way to make it work for the GCP use case. However, on one hand, we feed that this change slightly deviates the library's roadmap, and on the other hand we won't be able to test throughly the functionality and maintain it at this time, so we are sorry that we won't be able to accept this pull request. You are welcome to fork the Greykite repo and use the functionality on your use case. Feel free to open a new issue if you have more questions!

Best,
Kaixu
