### ISSUE TITLE
Positivity constraint for predictions

### ISSUE THREAD

**Issue by candalfigomoro** [linkedin/greykite#42]
With greykite/silverkite, is it possible to set a positivity constraint for predictions? Something similar to the "Approach 5" you can find here for prophet: https://github.com/facebook/prophet/issues/1668#issue-701631525

This is a common requirement for many business-related time series.

Thanks

**Comment by KaixuYang** [comment]
Hi @candalfigomoro by positive constraint, did you mean to make the predictions always positive? You could specify "min_admissible_value" in "SimpleSilverkiteTemplate.custom" and all negative values will be masked with 0.

**Comment by candalfigomoro** [comment]
Thank you
