### ISSUE TITLE
Getting Various Warnings while running time series prediction

### ISSUE THREAD

**Issue by Amatullah** [linkedin/greykite#43]
- I'm trying to fit  GreyKite Model to my time series data. 
- I have attached the csv file for reference.
- Even though the model works, it raises a bunch of warnings that I'd like to avoid.
- Since some of my target values are zero it tells me that MAPE is undefined.
- Also, since I'm only forecasting one step into the future, it gives me an UndefinedMetricWarning : R^2 score is not well-defined with less than two samples.'
- I have attached a few images displaying the warnings.
- Any help to get rid of these warnings would be appreciated!

- This is the code I'm using to fit the data:

`class GreyKiteModel(AnomalyModel):

    def __init__(self, *args,model_kwargs = {}, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.model_kwargs = model_kwargs
        
    def predict(self, df: pd.DataFrame, ) -> pd.DataFrame:
        """Takes in pd.DataFrame with 2 columns, dt and y, and returns a 
        pd.DataFrame with 3 columns, dt, y, and yhat_lower, yhat_upper.

        :param df: Input Dataframe with dt, y columns
        :type df: pd.DataFrame
        :return: Output Dataframe with dt, y, yhat_lower, yhat_upper 
        columns
        :rtype: pd.DataFrame
        """
        df = df.rename(columns = {"dt":"ds", "y":"y"})
        metadata = MetadataParam(time_col="ds", # ----> name of the time column 
                                 value_col="y", # ----> name of the value column 
                                 freq="D"       # ----> H" for hourly, "D" for daily, "W" for weekly, etc. 
                                )
        forecaster = Forecaster()  # Creates forecasts and stores the result
        result = forecaster.run_forecast_config(df=df, # result is also stored as forecaster.forecast_result
                                                config=ForecastConfig(model_template=ModelTemplateEnum.SILVERKITE.name,
                                                                      forecast_horizon=1,  # forecasts 1 step
                                                                      coverage=0.95,
                                                                      metadata_param=metadata 
                                                                      )
                                                )
        forecast_df = result.forecast.df
        forecast_df = forecast_df.drop(columns=['actual'])
        forecast_df.rename(columns={'ds':'dt',
                                    'forecast':'y', 
                                    'forecast_lower':'yhat_lower', 
                                    'forecast_upper':'yhat_upper' },
                           inplace=True)
        return forecast_df`

[df.csv](https://github.com/linkedin/greykite/files/7025180/df.csv)

![Screenshot from 2021-08-21 12-39-55](https://user-images.githubusercontent.com/22439823/130316293-f10c8590-8e6b-48ff-85bb-73d71a67f999.png)

![Screenshot from 2021-08-21 12-39-10](https://user-images.githubusercontent.com/22439823/130316294-38929040-1953-4213-9ffb-49a3fbca28aa.png)

**Comment by KaixuYang** [comment]
Hi @Amatullah Could you try
```
import warnings
warnings.filterwarnings('ignore')
```

**Comment by Amatullah** [comment]
I tried that and the warning do get suppressed. I'm looking for a way to not get these warning altogether. 
In my program I always need to forecast one step in to the future only, does that mean that the warning will always remain?

**Comment by KaixuYang** [comment]
Hi @Amatullah the library raises these warning whenever the condition meets, but actually you could specify message in `filterwarnings` for example
```
warnings.filterwarnings("ignore", message="y_true is constant")
```
You could suppress all specific warning you want to suppress at the beginning of your code.

**Comment by dromare** [comment]
I had the same problem with warnings about holidays, I was able to suppress those warnings by changing events=None to explicitly declare the dict:
<img width="238" alt="Capture4" src="https://user-images.githubusercontent.com/90710133/133746798-b5e87df1-ee72-4a8e-87eb-51ce5818245d.PNG">

Like you, my response has zero values so I am getting the same y_pred and MAPE-related warnings in the output. I have opened issue #51 on this because what we want is to be able to control the amount of metrics being computed rather than forcibly suppress useful warnings which are there to show us what may be going wrong.
