### ISSUE TITLE
Prophet template | KeyError: "['yhat_lower', 'yhat_upper'] not in index" | Set uncertainty_samples = 0

### ISSUE THREAD

**Issue by yowgwowang** [linkedin/greykite#46]
Hi

I want to use Prophet in the greykite template without coverage.
In the model components parameter, I set the uncertainty_samples = 0. 
Here is the screenshot:
![image](https://user-images.githubusercontent.com/66694357/131908908-c0d4b544-985f-46f4-82bc-7aff7ec34b11.png)

However, the forecast run error out saying it cannot find the "['yhat_lower', 'yhat_upper'] not in index".
I think there is a bug in the code?

![image](https://user-images.githubusercontent.com/66694357/131909052-a0923fbd-ef6f-4ab1-9d00-5350b2e9319d.png)

![image](https://user-images.githubusercontent.com/66694357/131909162-e6e0b3ed-e0b8-4850-b457-d4151b640eac.png)

**Comment by KaixuYang** [comment]
Hi @yowgwowang , currently coverage is required in `ProphetEstimator` through `Greykite`, but in the future we might make this optional. Meanwhile, you are welcome to submit a pull request to help us add this support if you would like to! The idea is to add a condition check to `prophet_estimator.py` line 299 to check if `yhat_lower` and `yhat_upper` is in the `pred_df`, and add them to `output_columns` only when they are in the df.

**Comment by KaixuYang** [comment]
Fixed in the next release.
