### ISSUE TITLE
Setting of "cv_max_splits" when using "fit_algorithm": "lasso"

### ISSUE THREAD

**Issue by dromare** [linkedin/greykite#50]
Hi all,

When setting fit_algorithm_params={"cv": 5} to use 5-fold CV with sklearn LassoCV() on the training set, how should the global parameter "cv_max_splits" be set up ? (either set it to zero, or to None - equivalent to 3 - or equal to 5 ?).

Best regards,
Dario

**Comment by sayanpatra** [comment]
Hi @dromare, the answer depends on the model you are running. In general, these parameters are independent. 

If you are using a single estimator you can set `cv_max_splits` to 0. If you are comparing multiple estimators/ models you can choose `cv_max_splits` to be a proper representation of your testing period.

If you need more model tuning guidance feel free to post your model configuration and a snippet of the data you are working with.

**Comment by dromare** [comment]
Thank you sayanpatra, that is what I wanted to know. So if we have a single estimator which chooses its hyperparameters by K-fold CV on the training set (say, LassoCV or RidgeCV) then if we set cv_max_splits = J, I believe we would end up doing (J times K)-fold CV on the training set.

**Comment by sayanpatra** [comment]
Yes, you are correct.

**Comment by dromare** [comment]
Great, thanks ! I will close this issue then.
