### ISSUE TITLE
"cv_selection_metric" & "cv_report_metrics"

### ISSUE THREAD

**Issue by dromare** [linkedin/greykite#51]
Hello all,

I am running the Greykite without cross-validation (cv_max_splits = 0) because I am using the LassoCV() algorithm which by itself uses 5-fold CV. The ForecastConfig() is as follows, in particular, evaluation_metric is all set to None because cv_max_splits = 0:

<img width="723" alt="Capture" src="https://user-images.githubusercontent.com/90710133/133300207-85feeeb7-d105-4373-82e1-630944b856c5.PNG">

However, the output on the console suggests that at least 3 metrics are evaluated. My response contains zeros so I do not want MAPE and MedAPE to be reported, and I do not want "Correlation" to be reported either. As a matter of fact, since the loss function in LassoCV() is MSE (L2-norm), I am not interested in anything rather than MSE, really. Unless the loss function in LassoCV() could be changed to MAE (L1-norm) in that case I would be interested in the MAE instead of MSE:

<img width="644" alt="Capture1" src="https://user-images.githubusercontent.com/90710133/133301420-607d3f44-94f6-42d5-92a9-fe7fd0d46841.PNG">

Do you have any suggestions please ?

Best regards,
Dario

**Comment by sayanpatra** [comment]
Hi,

Can you post your code please so that we can reproduce it?

**Comment by dromare** [comment]
Hi sayanpatra,

I believe this issue can be considered a duplicate of issue #43, which is still open. The basic question is: how can we control the amount of metrics being computed rather than forcibly suppress useful warnings which are there to show us what may be going wrong:

- The two warnings about **y_true** (MAPE and medAPE are undefined) most probably refer to the train period, because that is where my response has some zero values (no zero values in the forecast period)
- The warning about y_pred, instead, can either refer to the train period or the forecast period ( because this particular model fits the intercept term, which also becomes the forecast)

I know that my response may contain zeros values, hence I would like to prevent the algorithm from calculating an undefined MAPE rather than letting it go ahead and throw a warning. Similarly, I am not interested in the correlation calculation, so I would like the algorithm to be spared that task and effort too.

**Comment by sayanpatra** [comment]
When you pass `cv_selection_metric` as `None` in `EvaluationMetricParam`, it computes a default set of metrics. I believe you will not get those error messages if you add the RMSE as the evaluation metric as follows:

```
from linkedin.greykite.common.evaluation import EvaluationMetricEnum

evaluation_metric = EvaluationMetricParam(
    cv_selection_metric=EvaluationMetricEnum.RootMeanSquaredError.name
)

config = ForecastConfig(
metadata_param=metadata,
...,
evaluation_metric_param=evaluation_metric
)
```

**Comment by dromare** [comment]
I did as you said but I am still getting MAPE and MedAPE messages, whether I use the RMSE or the MAE metric (MAE metric in screenshot below)
<img width="412" alt="Capture5" src="https://user-images.githubusercontent.com/90710133/135129854-37259d9f-eef9-4627-8820-d0a79f99805d.PNG">
:

**Comment by sayanpatra** [comment]
I can not respond based on partial code. As I said before if you need help, post your full code.

**Comment by dromare** [comment]
I found out that these warnings come from the error metrics on the forecast results (and the backtest results if test_horizon=0):
![image](https://user-images.githubusercontent.com/90710133/135836176-681d0a72-019a-4ef0-a7f7-b9086259903a.png)
```
result.forecast.train_evaluation
result.forecast.test_evaluation
result.backtest.train_evaluation
result.backtest.test_evaluation
```
