### ISSUE TITLE
`get_default_origin_for_time_vars` throws a `KeyError` if the leading time series values are null

### ISSUE THREAD

**Issue by vandonova** [linkedin/greykite#54]
`get_default_origin_for_time_vars` throws a `KeyError` if the leading time series value is `np.nan`. 

https://github.com/linkedin/greykite/blob/ce59715ecd3709281c83fac9aef3ce4bb28634ef/greykite/common/features/timeseries_features.py#L75

For example:
```
from greykite.sklearn.estimator.simple_silverkite_estimator import SimpleSilverkiteEstimator

params =  {'forecast_horizon': 1, 
 'uncertainty_dict': {'uncertainty_method': 'simple_conditional_residuals', 
                      'params': {'conditional_cols': ['dow'], 
                                 'quantile_estimation_method': 'normal_fit', 
                                 'sample_size_thresh': 5, 
                                 'small_sample_size_method': 'std_quantiles', 
                                 'small_sample_size_quantile': 0.99}}, 
 'fit_algorithm_dict': {'fit_algorithm': 'elastic_net', 
                        'fit_algorithm_params': {
                            'l1_ratio': [0.1,0.5,0.7,0.9,0.95,0.99,1]
                        }
                        }, 
 'holiday_lookup_countries': ['US'], 
 'changepoints_dict': {'method': 'auto', 
                       'regularization_strength': None, 
                       'actual_changepoint_min_distance': '7D', 
                       'potential_changepoint_distance': '3D', 
                       'yearly_seasonality_order': 6, 
                       'no_changepoint_proportion_from_end': 0.18}, 
 'yearly_seasonality': 'auto', 
 'quarterly_seasonality': False, 
 'monthly_seasonality': False, 
 'weekly_seasonality': 'auto', 
 'daily_seasonality': 'auto', 
 'coverage': 0.95
 }
df = pd.DataFrame({'ds':pd.date_range('2021-08-18', periods=20), 'y': range(1,21)})
m = SimpleSilverkiteEstimator(**params)
m.fit(df, time_col="ds", value_col="y")
```
will fit and predict as expected, however, 
```
df.loc[0, 'y'] = np.nan
m.fit(df, time_col="ds", value_col="y")
```
will throw a `*** KeyError: 0`

This happens because of the `[0]` indexing. When null values are dropped so is the index `0` which results in the `KeyError. This issue can be addressed by using `iloc[0]` instead to access the first row in the dataframe.

Let me know if this is intentional - happy to open a PR otherwise!

Vicky

**Comment by KaixuYang** [comment]
Hi @vandonova thanks for the detailed explanation! Yeah I agree that changing to `.iloc[0]` would be a more general solution. Greykite has pipeline which does droping/interpolating NANs and resetting indices, so if you call the library from the templates level this won't be an issue, but yeah if you directly use the estimators, there can be this issue. It's greatly appreciated if you can help fix this issue by submitting a PR, thanks!

Kaixu

**Comment by KaixuYang** [comment]
Fixed in the next release.
