### ISSUE TITLE
Compatibility with plotly 5

### ISSUE THREAD

**Issue by fleimgruber** [linkedin/greykite#63]
Are there plans to update to a newer plotly API? A quick look at https://github.com/linkedin/greykite/search?q=plotly shows mainly `plotly.offline`, `plotly.colors` and `plotly.graph_objs` usage. Has the code changed in this regard since the version was restricted in https://github.com/linkedin/greykite/blob/master/setup.py#L23?

**Comment by KaixuYang** [comment]
Hi @fleimgruber we are planning on a new release soon where we will upgrade the `plotly` version.

Kaixu

**Comment by KaixuYang** [comment]
Hi @fleimgruber we just released `greykite==0.3.0` which supports `plotly>=4.1.2` including version 5.
