### ISSUE TITLE
Wrong assignment to summary prediction categories

### ISSUE THREAD

**Issue by dromare** [linkedin/greykite#68]
Hi all,

I have added 69 **regressors** to **ModelComponentsParam**, so my model instance is as follows:
**ModelComponentsParam**(autoregression={'autoreg_dict': 'auto'}, changepoints={'changepoints_dict': [None, {'method': 'auto'}]}, custom={'fit_algorithm_dict': [{'fit_algorithm': 'elastic_net', 'fit_algorithm_params': {'l1_ratio': array([0.01, 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.6 , 0.7 , 0.8 , 0.9 , 0.99]), 'n_alphas': 100, 'alphas': None, 'fit_intercept': True, 'cv': None, 'tol': 0.001, 'max_iter': 1000}}], 'feature_sets_enabled': 'auto', 'min_admissible_value': None, 'max_admissible_value': None}, events={'holiday_lookup_countries': [], 'holidays_to_model_separately': None, 'holiday_pre_num_days': 2, 'holiday_post_num_days': 2, 'holiday_pre_post_num_dict': None, 'daily_event_df_dict': None}, growth={'growth_term': None}, hyperparameter_override={'input__response__outlier__use_fit_baseline': False, 'input__response__outlier__z_cutoff': None, 'input__response__null__impute_algorithm': None, 'input__regressors_numeric__outlier__use_fit_baseline': False, 'input__regressors_numeric__outlier__z_cutoff': None, 'input__regressors_numeric__null__impute_algorithm': None, 'input__regressors_numeric__normalize__normalize_algorithm': 'RobustScaler', 'input__regressors_numeric__normalize__normalize_params': {'quantile_range': (10.0, 90.0)}, 'degenerate__drop_degenerate': False}, **regressors**={'regressor_cols': ['ownSame_5_NET_PRICE_BAG', 'media_total_spend', 'Discount_Depth', 'weather_wghtd_avg_tmp_flslk_2m_f_max_low', 'ownSame_3_NET_PRICE_BAG', 'media_tv_traditional', 'hol_EasterSunday', 'cg_STRNGNCY_LGCY_INDX_MEAN', 'hol_RestorationofIndependence_LAG1', 'NET_PRICE_BAG', 'hol_AllSaintsDay_LAG3', 'hol_holiday_count', 'hol_AssumptionDay_lead4', 'hol_AssumptionDay_lead2', 'cc_AVG_IR_MEAN', 'hol_spain_perc_wknd', 'media_digital', 'hol_CorpusChristi_LAG2', 'hol_AssumptionDay_lead3', 'hol_CorpusChristi_LAG3', 'inp_actual_inventory', 'weather_wghtd_avg_tmp_flslk_2m_f_min_high', 'gm_AVG_PRKS_PCNT_CHNG_FRM_BSLNE_MEAN', 'weather_wghtd_avg_tmp_flslk_2m_f_max_high', 'hol_holiday_count_lead4', 'hol_spain_hol_flag', 'weather_wghtd_avg_tmp_flslk_2m_f_mean_mid', 'weather_wghtd_avg_tmp_flslk_2m_f_mean_high', 'hol_ConstitutionDay_lead2', 'hol_portugal_perc_longwknd', 'gm_AVG_RSDNTL_AND_PHRMCY_PCNT_CHNG_FRM_BSLNE_MEAN', 'weather_wghtd_avg_tmp_flslk_2m_f_min_low', 'weather_presence_of_snow', 'hol_ImmaculateConception', 'hol_portugal_fri_mon_flag', 'ownSame_2_NET_PRICE_BAG', 'gm_AVG_RTL_AND_RCRTN_PCNT_CHNG_FRM_BSLNE_MEAN', 'hol_spain_fri_mon_flag', 'hol_NationalDay_LAG4', 'Dollar_Discount', 'hol_portugal_perc_wknd', 'weather_wghtd_avg_tmp_flslk_2m_f_min_mid', 'hol_NationalDay_LAG3', 'ownSame_1_NET_PRICE_BAG', 'hol_portugal_hol_flag', 'cg_STRNGNCY_INDX_MEAN', 'hol_ConstitutionDay', 'weather_wghtd_avg_tmp_flslk_2m_f_mean_low', 'hol_Epiphany_lead4', 'cg_CNTNMT_HLTH_INDX_MEAN', 'cc_AVG_CFR_MEAN', 'hol_spain_perc_longwknd', 'weather_wghtd_avg_tmp_flslk_2m_f_max_mid', 'cg_GOVT_RSPNS_INDX_MEAN', 'inp_projected_inventory', 'ph_Unemployment_persons', 'ownSame_4_NET_PRICE_BAG', 'cc_REC_MEAN', 'inp_actual_inventory_flag', 'hol_NationalDay_LAG2', 'hol_AssumptionDay_lead1', 'hol_GoodFriday', 'hol_CorpusChristi_LAG4', 'hol_spain_wknd_flag', 'hol_portugal_wknd_flag', **'weather_wghtd_avg_cld_cvr_tot_pct_max_mid', 'weather_wghtd_avg_cld_cvr_tot_pct_max_low', 'weather_wghtd_avg_cld_cvr_tot_pct_max_high', 'media_total_spend_lag4'**]}, lagged_regressors=None, seasonality={'yearly_seasonality': 'auto', 'quarterly_seasonality': 'auto', 'monthly_seasonality': 'auto', 'weekly_seasonality': False, 'daily_seasonality': False}, uncertainty=None)

When checking the model output summary, I only find 65 regressors in the **regressor_features** category. Of the missing 4, 3 have ended up in the **trend_features** category, and 1 in the **lag_features** category:
```
summary = result.model[-1].summary()
for key, val in summary.pred_category.items():
    print(key)
    print(len(val))
    print(val)
```
intercept
1
['Intercept']
time_features
0
[]
event_features
0
[]
**trend_features**
3
[**'weather_wghtd_avg_cld_cvr_tot_pct_max_mid', 'weather_wghtd_avg_cld_cvr_tot_pct_max_low', 'weather_wghtd_avg_cld_cvr_tot_pct_max_high'**]
seasonality_features
44
['sin1_tom_monthly', 'cos1_tom_monthly', 'sin2_tom_monthly', 'cos2_tom_monthly', 'sin1_toq_quarterly', 'cos1_toq_quarterly', 'sin2_toq_quarterly', 'cos2_toq_quarterly', 'sin3_toq_quarterly', 'cos3_toq_quarterly', 'sin4_toq_quarterly', 'cos4_toq_quarterly', 'sin5_toq_quarterly', 'cos5_toq_quarterly', 'sin1_ct1_yearly', 'cos1_ct1_yearly', 'sin2_ct1_yearly', 'cos2_ct1_yearly', 'sin3_ct1_yearly', 'cos3_ct1_yearly', 'sin4_ct1_yearly', 'cos4_ct1_yearly', 'sin5_ct1_yearly', 'cos5_ct1_yearly', 'sin6_ct1_yearly', 'cos6_ct1_yearly', 'sin7_ct1_yearly', 'cos7_ct1_yearly', 'sin8_ct1_yearly', 'cos8_ct1_yearly', 'sin9_ct1_yearly', 'cos9_ct1_yearly', 'sin10_ct1_yearly', 'cos10_ct1_yearly', 'sin11_ct1_yearly', 'cos11_ct1_yearly', 'sin12_ct1_yearly', 'cos12_ct1_yearly', 'sin13_ct1_yearly', 'cos13_ct1_yearly', 'sin14_ct1_yearly', 'cos14_ct1_yearly', 'sin15_ct1_yearly', 'cos15_ct1_yearly']
**lag_features**
1
[**'media_total_spend_lag4'**]
**regressor_features**
65
['ownSame_5_NET_PRICE_BAG', 'media_total_spend', 'Discount_Depth', 'weather_wghtd_avg_tmp_flslk_2m_f_max_low', 'ownSame_3_NET_PRICE_BAG', 'media_tv_traditional', 'hol_EasterSunday', 'cg_STRNGNCY_LGCY_INDX_MEAN', 'hol_RestorationofIndependence_LAG1', 'NET_PRICE_BAG', 'hol_AllSaintsDay_LAG3', 'hol_holiday_count', 'hol_AssumptionDay_lead4', 'hol_AssumptionDay_lead2', 'cc_AVG_IR_MEAN', 'hol_spain_perc_wknd', 'media_digital', 'hol_CorpusChristi_LAG2', 'hol_AssumptionDay_lead3', 'hol_CorpusChristi_LAG3', 'inp_actual_inventory', 'weather_wghtd_avg_tmp_flslk_2m_f_min_high', 'gm_AVG_PRKS_PCNT_CHNG_FRM_BSLNE_MEAN', 'weather_wghtd_avg_tmp_flslk_2m_f_max_high', 'hol_holiday_count_lead4', 'hol_spain_hol_flag', 'weather_wghtd_avg_tmp_flslk_2m_f_mean_mid', 'weather_wghtd_avg_tmp_flslk_2m_f_mean_high', 'hol_ConstitutionDay_lead2', 'hol_portugal_perc_longwknd', 'gm_AVG_RSDNTL_AND_PHRMCY_PCNT_CHNG_FRM_BSLNE_MEAN', 'weather_wghtd_avg_tmp_flslk_2m_f_min_low', 'weather_presence_of_snow', 'hol_ImmaculateConception', 'hol_portugal_fri_mon_flag', 'ownSame_2_NET_PRICE_BAG', 'gm_AVG_RTL_AND_RCRTN_PCNT_CHNG_FRM_BSLNE_MEAN', 'hol_spain_fri_mon_flag', 'hol_NationalDay_LAG4', 'Dollar_Discount', 'hol_portugal_perc_wknd', 'weather_wghtd_avg_tmp_flslk_2m_f_min_mid', 'hol_NationalDay_LAG3', 'ownSame_1_NET_PRICE_BAG', 'hol_portugal_hol_flag', 'cg_STRNGNCY_INDX_MEAN', 'hol_ConstitutionDay', 'weather_wghtd_avg_tmp_flslk_2m_f_mean_low', 'hol_Epiphany_lead4', 'cg_CNTNMT_HLTH_INDX_MEAN', 'cc_AVG_CFR_MEAN', 'hol_spain_perc_longwknd', 'weather_wghtd_avg_tmp_flslk_2m_f_max_mid', 'cg_GOVT_RSPNS_INDX_MEAN', 'inp_projected_inventory', 'ph_Unemployment_persons', 'ownSame_4_NET_PRICE_BAG', 'cc_REC_MEAN', 'inp_actual_inventory_flag', 'hol_NationalDay_LAG2', 'hol_AssumptionDay_lead1', 'hol_GoodFriday', 'hol_CorpusChristi_LAG4', 'hol_spain_wknd_flag', 'hol_portugal_wknd_flag']
interaction_features
0
[]

Best,
Dario

**Comment by reidfalconer** [comment]
@dromare good catch! It looks like a regex bug [here](https://github.com/linkedin/greykite/blob/e0a81c4b4f66241937b2f6883ef1b89b60b494a9/greykite/algo/common/col_name_utils.py#L274-L289) (the constants are defined [here](https://github.com/linkedin/greykite/blob/e0a81c4b4f66241937b2f6883ef1b89b60b494a9/greykite/common/constants.py)). I think this regex check needs to be more strict otherwise any feature with `"lag_"` or `"cp\\d"`  (order independent) will be added to the `lag_features` or `trend_features` respectively.

**Comment by dromare** [comment]
@reidfalconer yes ! Regressor features that are in the other categories are removed (from line 294 of the code you provided a link to) whereas a safer option would be to remove trend, seasonality etc. features that are in the regressor category.

**Comment by KaixuYang** [comment]
Hi @dromare and @reidfalconer , thanks for reporting this issue and thanks for the discussion to figure out the root cause. Yeah it looks like we need to improve the regex we use to identify categories. One fix I can think of is to handle it [here](https://github.com/linkedin/greykite/blob/e0a81c4b4f66241937b2f6883ef1b89b60b494a9/greykite/sklearn/estimator/base_silverkite_estimator.py#L419), to explicitly specify `regressor_cols` in the `create_pred_category` function, and let it keep whatever in `regressor_cols` in the regressors category. The `regressor_cols` parameter has whatever is specified as regressors in the model input. Then it can create categories for the rest of the features.

**Comment by dromare** [comment]
Thank you @KaixuYang, as a temporary fix I have renamed regressors containing 'pct' to 'pc1t', and 'lag' to 'laag'. It works.
