### ISSUE TITLE
pip3 install fail, osqp

### ISSUE THREAD

**Issue by dirknbr** [linkedin/greykite#71]
I get a very long (compile) error, running a unix system, py 3.9

```
Building wheels for collected packages: osqp
  Building wheel for osqp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bnj3xtxq/osqp_b69b1cb707df4d75a5c87bef4ad63a49/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bnj3xtxq/osqp_b69b1cb707df4d75a5c87bef4ad63a49/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-u65nf2w9
       cwd: /tmp/pip-install-bnj3xtxq/osqp_b69b1cb707df4d75a5c87bef4ad63a49/
  Complete output (125 lines):
  running bdist_wheel
  running build
  running build_py
```

**Comment by sayanpatra** [comment]
Our library requires cmake3 to build. Please run the following to upgrade:

```
# sudo yum remove cmake -y  # optional, uninstall existing cmake
sudo yum install cmake3
sudo ln -s /usr/bin/cmake3 /usr/bin/cmake
```

**Comment by dirknbr** [comment]
Thanks that worked, I used apt-get to install cmake

**Comment by KathyGCY** [comment]
Also, if you don't have root access and cannot do any command with sudo, here's the fix:

1. In jupyter lab:
```
import platform
print(platform.system())
```
(for me this shows Linux)

2. Go to cmake download page here: https://cmake.org/download/
download the corresponding file for your system (for me the linux file)
Upload that file to jupyter lab

3. Open a terminal  and cd into where the file has been uploaded to.
`tar -xf cmake*.tar.gz`
Okay you now have a folder called “cmake-3.24.1” or whatever version you downloaded. Now type:
```
cd cmake-3.24.1
./configure --prefix=$HOME
make
make install
```
Takes forever to complete but after that pip install will work
