### ISSUE TITLE
How to extract future trend?

### ISSUE THREAD

**Issue by sasakigao** [linkedin/greykite#75]
Hi everyone, I have tried some methods to extract future trend from a trained model but all failed. One is extracting data from `result.forecast.plot_components`, but they are only training set without future components. Then I tried to build features directly from original time series and fit the trend, but it's too hard to transform the features from origin time series. 
Any idea about it? Thanks a lot~

**Comment by sayanpatra** [comment]
Hi,

We have an update for this. Now you can get custom / flexible breakdowns as per your need from the model both for fitted and predicted values. We call them forecast breakdowns. See documentation here: https://linkedin.github.io/greykite/docs/0.4.0/html/gallery/quickstart/02_interpretability/0200_interpretability.html
