### ISSUE TITLE
support python 3.10

### ISSUE THREAD

**Issue by IlanEiland** [linkedin/greykite#76]

**Comment by tmeshorer** [comment]
First, thanks for the wonderful library. 

Second, Is there any update on this bug? 

Third, is there a plan to support a higher version of pandas?

Thanks.

**Comment by callmegar** [comment]
pandas is also an issue for me, very difficult to combine models and libraries with a version of pandas that old

**Comment by samuelefiorini** [comment]
According to [link](https://linkedin.github.io/greykite/docs/0.5.0/html/pages/changelog/changelog.html), version 0.5.0 solves this issue.

**Comment by KaixuYang** [comment]
Hello everyone, as @samuelefiorini mentioned above we have released 0.5.0 that supports python 3.10. I'm closing this issue.
