### ISSUE TITLE
What is SilverKite and reconcile?(Will like to help in Example Notebooks)

### ISSUE THREAD

**Issue by satya-pattnaik** [linkedin/greykite#8]
Hi, I had some questions
Q1] Is the SilverKite method supposed to take any regressor(like Xgboost) and convert that to an AutoRegressor(based on lags)?
Q2]Is the reconcile method meant to explore Hierarchical Forecasting as per [Hyndman's](https://otexts.com/fpp2/hierarchical.html)?

It will be great if I can be any help creating example notebooks around the ```reconcile``` and ```Silverkite```.

**Comment by al-bert** [comment]
Hi Satya,

To answer Q2:

The reconcile method imposes additive constraints (not necessarily hierarchical) on a set of forecasts, in a way that hopefully preserves or even improves forecast quality. It's a newer feature so we don't have a tutorial yet, but you are welcome to try it out. Our docstrings are fairly comprehensive, and you can check test cases for examples.

Albert
