### ISSUE TITLE
can t set time col in metadata

### ISSUE THREAD

**Issue by brusand** [linkedin/greykite#87]
Hi,
your framework look great, but for my first code, i can t set a time  col, i always have have an erreur (not in column input or ValueError: NaTType does not support strftime
my original timeframe col :
    df['date'] = pd.to_datetime( df.index, unit='s')
    df['ts'] =  pd.to_datetime(df.index, errors='coerce',  unit='s')#
    
    #df = df.loc[:,['date','high','low','open','close','volume', 'updown', 'ses_02', 'ses_07', 'ses_13', 'ses_20','ses_30','ses_40','ses_50','ses_60','ses_diff','ses_close_diff', 'close_ses_updown']]
    df = df.set_index('date')
    df.index = pd.to_datetime(df.index,unit='ns')
    
    
    values
    

open | high | low | close | ts | ses_02 | ses_07 | ses_13 | ses_20 | ses_30 | ses_40 | ses_50 | ses_60
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

22903.00 | 22909.13 | 22882.08 | 22888.63 | 2022-08-05 20:13:00 | 22888.6300 | 22888.6300 | 22888.6300 | 22888.630 | 22888.630 | 22888.630 | 22888.630 | 22888.630
22888.63 | 22904.99 | 22884.99 | 22897.86 | 2022-08-05 20:14:00 | 22888.8146 | 22889.2761 | 22889.8299 | 22890.476 | 22891.399 | 22892.322 | 22893.245 | 22894.168
22897.86 | 22909.80 | 22894.37 | 22909.65 | 2022-08-05 20:15:00 | 22898.0958 | 22898.6853 | 22899.3927 | 22900.218 | 22901.397 | 22902.576 | 22903.755 | 22904.934
22909.64 | 22945.94 | 22905.66 | 22941.52 | 2022-08-05 20:16:00 | 22910.2874 | 22911.8809 | 22913.7931 | 22916.024 | 22919.211 | 22922.398 | 22925.585 | 22928.772
22941.37 | 22966.78 | 22934.74 | 22941.42 | 2022-08-05 20:17:00

metadata
metadata = MetadataParam(
 time_col="ts",   # ----> name of the time column 
 value_col="close",  # ----> name of the value column 
 freq="M"           #"MS" for Montly at start date, "H" for hourly, "D" for daily, "W" for weekly, etc.
)

error
File /usr/local/lib/python3.9/site-packages/greykite/framework/templates/forecaster.py:375, in Forecaster.run_forecast_config(self, df, config)
    349 def run_forecast_config(
    350         self,
    351         df: pd.DataFrame,
    352         config: Optional[ForecastConfig] = None) -> ForecastResult:
    353     """Creates a forecast from input data and config.
    354     The result is also stored as ``self.forecast_result``.
    355 
   (...)
    373         according to the ``df`` and ``config`` configuration parameters.
    374     """
...
    173 period = min_gap_in_seconds(df=fit_df, time_col=TIME_COL)

File pandas/_libs/tslibs/nattype.pyx:72, in pandas._libs.tslibs.nattype._make_error_func.f()

ValueError: NaTType does not support strftime

i use the last version of greykite with python 3.9
Thx

**Comment by sayanpatra** [comment]
Can you try the following?

```
#df = df.loc[:,['date','high','low','open','close','volume', 'updown', 'ses_02', 'ses_07', 'ses_13', 'ses_20','ses_30','ses_40','ses_50','ses_60','ses_diff','ses_close_diff', 'close_ses_updown']]
df = df.reset_index(drop=True)

metadata = MetadataParam(
  time_col="ts", # ----> name of the time column
  value_col="close", # ----> name of the value column
  freq="T" 
)
```

"T" refers to pandas DateTime index minute: https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.minute.html
