### ISSUE TITLE
Parallel execution on Spark,

### ISSUE THREAD

**Issue by strateg17** [linkedin/greykite#88]
Taking into account your experience, described in this paper: [Greykite: Deploying Flexible Forecasting at Scale at LinkedIn](https://arxiv.org/pdf/2207.07788.pdf,)  I am going to extend my forecasts for more then 100 time series using Spark and databricks. The only possible example is for prophet: https://www.databricks.com/blog/2020/01/27/time-series-forecasting-prophet-spark.html. But with such an approach it is impossible to save separate models correctly. Is it possible at this moment to train and save GreyKite with Parallel execution on spark?

**Comment by sayanpatra** [comment]
No `Spark` architecture is built in the `greykite` package. However, you can follow the `Prophet` example to create, train, and save separate models. In fact, we use a similar Spark implementation internally at LinkedIn. Feel free to ping in this thread if you need more help on the issue.

**Comment by strateg17** [comment]
> No `Spark` architecture is built in the `greykite` package. However, you can follow the `Prophet` example to create, train, and save separate models. In fact, we use a similar Spark implementation internally at LinkedIn. Feel free to ping in this thread if you need more help on the issue.

Thank you, in fact, I'm currently using the same example for group forecasting.
