### ISSUE TITLE
Version without Facebook Prophet

### ISSUE THREAD

**Issue by AlexMV12** [linkedin/greykite#9]
Hello,

Thank you for open-sourcing this library and for your effort. It's great.

I would like to add Greykite as an available model for one library I am developing.
However, given that I already use Facebook Prophet, adding Greykite creates a series of conflicts (I use the latest Prophet version, etc).
I am interested in the Silverkite model; so, my suggestion is to add the possibility to install Greykite without the Prophet part. I don't know if it's possible, or if it is not in your plans.

Thank you again.
Alessandro

**Comment by Reza1317** [comment]
Hi Alessandro,

This is a valid concern / request. We do plan to address this issue. One option is to remove prophet from the library in later versions. We will explore the solutions and hopefully this is addressed in next releases.

Thanks
Reza
