### ISSUE TITLE
Support for pandas 1.3

### ISSUE THREAD

**Issue by BernardoSandiQB** [linkedin/greykite#96]
Hey team,

Is there a timeline to add support for pandas 1.3?  https://github.com/linkedin/greykite/blob/master/setup.py#L21
I'm having issues integrating with other packages that only work with pandas 1.3 and above.

Thank you!

**Comment by amyfei2015** [comment]
Hi! Thanks for the questions! We are still working on this, please stay tuned. Thanks!

**Comment by KaixuYang** [comment]
Hi @BernardoSandiQB we have released greykite 0.5.0 that supports pandas >= 1.5 and < 2.0.
