### ISSUE TITLE
regularization_strength Default value

### ISSUE THREAD

**Issue by KathyGCY** [linkedin/greykite#98]
Hi! 
From this tech doc [here](https://linkedin.github.io/greykite/docs/0.3.0/html/gallery/quickstart/0200_changepoint_detection.html?highlight=regularization_strength#detect-trend-change-points) it seems the default value for regularization_strength  is NONE.
But I was testing it and trying to figure out what exactly is NONE.
And I tried to loop through from 0.0 to 1.0 by 0.1. And I failed to replicate this NONE.
I was wondering if the default NONE is a special value?
Thank you!
![Picture1](https://user-images.githubusercontent.com/14912791/215583270-46b14b95-8b91-46ca-9b25-4f5ffe72ace8.png)

**Comment by KaixuYang** [comment]
Hi @KathyGCY , the changespoints are identified with adaptive lasso. The regularization parameter is on the log scale of a predefined range of the original regularization parameters. If you specify None for that, it will do an cv on the adaptive lasso, where the best parameter chosen may not match exactly one of the 0.1, ..., 1.

Kaixu
