### ISSUE TITLE
Support custom metrics for cross validation

### ISSUE THREAD

**Issue by ArcticSublime** [linkedin/greykite#99]
Hi all, 

I'd like to use a custom metric like SDRMSE as a `cv_selection_metric` and also to include it to the `cv_result_metrics`. Is there any easy way to do this? I could set my own function as a `score_func` in pipeline parameters but I couldn't find an easy way to add it in the cv result. It would also be great if I could include it as historical evaluation metrics.

Thanks!

**Comment by sayanpatra** [comment]
Great question. You can do this by adding the SDRMSE metric in the following file: https://github.com/linkedin/greykite/blob/master/greykite/common/evaluation.py

Follow these steps:
1. Add the metric definition. Follow str structure of the `root_mean_squared_error` metric in line 464. The function signature should be:
```
@add_finite_filter_to_scorer
def metric_name(y_true, y_pred) -> float:
     < metric logic> 
```
2. Add the metric to `EvaluationMetricEnum` class, follow the `RootMeanSquaredError` example in line 944. It should be one liner:
```
MetricName = (metric_name, False, "metric")
```
Now you can call this function via `cv_selection_metric = EvaluationMetricEnum.MetricName.name` parameter in `EvaluationMetricParam`. This metric should be automatically reported. If it does not, you can enforce it via `cv_report_metrics = EvaluationMetricEnum.MetricName.name`.

Of course, replace `metric_name` etc. with a suitable naming of your choice. Let us know if it works.

**Comment by ArcticSublime** [comment]
Hi @sayanpatra, thank you for your reply. I followed your instructions and it worked fine!
I had to edit the code in the library this time, but it would be nicer to have a registration feature to add user metrics without having to edit the library.
